[project]
name = "process.os_writer"
requires-python = ">=3.10"
version = "0.0.1"

[tool.pytest.ini_options]
addopts = ["--asyncio-mode=auto", "--import-mode=importlib"]
testpaths = "test/"
pythonpath = ["../lib/src/", "src/"]